name: Deploy
on:
  # Keep this for someday in the future
#  workflow_dispatch:
#    inputs:
#      image-tag:
#        required: true
#        type: string
#        description: Docker tag
#      env-name:
#        required: true
#        type: choice
#        description: Environment name
#        options:
#          - dev
#          - test
#          - uat
#          - stage
#          - prod
#          - prod-dr

  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
        description: Docker tag
    secrets:
      slack-webhook:
        required: true

permissions:
  id-token: write
  contents: read


jobs:
  setup-vars:
    uses: ./.github/workflows/_setup.yaml
    with:
      env-name: ${{ inputs.env-name }}

  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@v8
        id: set-matrix
        with:
          result-encoding: string
          script: |
            let matrix = [{ "name": "report-server", "task-def": "report_server", "service": "report-server", "container": "report_server" }]
            if ("${{ inputs.env-name }}" == "prod") {
              matrix.push({ "name": "ped-report-server", "task-def": "ped_screener_report_server", "service": "ped-screener-report-server", "container": "report_server" })
            }
            return JSON.stringify(matrix);

  deploy:
    runs-on: ubuntu-latest
    needs: [setup-vars, setup-matrix]

    name: Deploy ${{ matrix.apps.name }}
    strategy:
      fail-fast: false
      matrix:
        apps: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    env:
      AWS_REGION: ${{ needs.setup-vars.outputs.region }}

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ needs.setup-vars.outputs.role }}
          role-session-name: OIDC-GHA-session-deploy
          aws-region: ${{ needs.setup-vars.outputs.region }}

      - name: Download task definition
        if: ${{ inputs.env-name }}
        run: |
          aws ecs describe-task-definition --task-definition ${{ matrix.apps.task-def }} --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ matrix.apps.container }}
          image: ${{ needs.setup-vars.outputs.ecr }}/report-server:${{ inputs.image-tag }}
          environment-variables: |
            BUILD_VERSION=${{ inputs.image-tag }}
            DD_VERSION=${{ inputs.image-tag }}
            SENTRY_RELEASE=${{ inputs.image-tag }}
          docker-labels: |
            com.datadoghq.tags.version=${{ inputs.image-tag }}

      - name: Update Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ matrix.apps.service }}
          cluster: ${{ needs.setup-vars.outputs.cluster }}
          wait-for-service-stability: true


  on-deploy-failure:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && (needs.deploy.result == 'failure' || needs.deploy.result == 'timed_out') }}
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v6
      - name: "Send Slack message on failure"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_WEBHOOK: ${{ secrets.slack-webhook }}
          MSG_MINIMAL: actions url
          SLACK_TITLE: Report Server Deploy Failed to ${{ inputs.env-name }}
          SLACK_MESSAGE: '🚨 Error when executing deployment!'

  on-deploy-success:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && (needs.deploy.result == 'success') }}
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v6
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::917902836630:role/github-oidc-ssm-version
          role-session-name: OIDC-GHA-session-version
          aws-region: us-east-1
      - name: Store version in SSM
        run: |
          aws ssm put-parameter \
                  --name "/curious/app/report-server/${{ inputs.env-name }}/version" \
                  --value "${{ inputs.image-tag }}" \
                  --type "String" \
                  --overwrite
      - name: "Send Slack message on success"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: success
          SLACK_WEBHOOK: ${{ secrets.slack-webhook }}
          MSG_MINIMAL: actions url
          SLACK_TITLE: Report Server Deployed to ${{ inputs.env-name }}
          SLACK_MESSAGE: '🚀 Deployment was successful.  Version: *${{ inputs.image-tag }}*'
