
name: Create Dev Release
on:
  workflow_dispatch: {}
  push:
    branches:
      - develop


concurrency:
  cancel-in-progress: true
  group: report-server-dev

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Docker Build and Push
    uses: ./.github/workflows/_build.yaml
    permissions:
      id-token: write
      contents: read
    with:
      image-tag: latest

  deploy:
    name: Deploy to Dev
    needs: [ build ]
    uses: ./.github/workflows/_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      image-tag: latest
      env-name: dev
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK_DEPLOY_TO_DEV }}

